name: flutter_basic_utils_ultra
description: "A set of small Flutter utilities."
version: 0.0.2
homepage: https://github.com/elieonline/flutter_basic_util
repository: https://github.com/elieonline/flutter_basic_util
license: MIT

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dlibphonenumber: ^1.1.45
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
